from typing import Protocol
from src.domain.entities import Post
from uuid import UUID

class PostRepository(Protocol):
    async def get_by_id(self, post_id: UUID) -> Post | None: ...
    async def save(self, post: Post) -> None: ...
    async def update(self, post: Post) -> None: ...
    async def delete(self, post_id: UUID) -> bool: ...