from typing import Protocol
from uuid import UUID

class CacheStorage(Protocol):
    async def get(self, post_id: UUID) -> dict | None: ...
    async def set(self, post_id: UUID, post_dict: dict) -> None: ...
    async def invalidate(self, post_id: UUID) -> None: ...
